services:
  - type: web
    name: fastapi-react-hcp-crm
    env: python
    region: oregon
    plan: free
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
    envVars:
      - key: PYTHONPATH
        value: .
